use_frameworks!

target 'SNViewPullable_Example' do
  pod 'SNViewPullable', :path => '../'

  target 'SNViewPullable_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
